/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SignInRouteImport } from './pages/sign-in'
import { Route as HistoryRouteImport } from './pages/history'
import { Route as CallbackRouteImport } from './pages/callback'
import { Route as IndexRouteImport } from './pages/index'
import { Route as TestsSlugRouteImport } from './pages/tests.$slug'
import { Route as AttemptsAttemptIdTimeUpRouteImport } from './pages/attempts.$attemptId.time-up'
import { Route as AttemptsAttemptIdRunRouteImport } from './pages/attempts.$attemptId.run'
import { Route as AttemptsAttemptIdReviewRouteImport } from './pages/attempts.$attemptId.review'
import { Route as AttemptsAttemptIdResultRouteImport } from './pages/attempts.$attemptId.result'
import { Route as AttemptsAttemptIdHandInRouteImport } from './pages/attempts.$attemptId.hand-in'
import { Route as AttemptsAttemptIdSectionsSectionIdRulesRouteImport } from './pages/attempts.$attemptId.sections.$sectionId.rules'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSlugRoute = TestsSlugRouteImport.update({
  id: '/tests/$slug',
  path: '/tests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdTimeUpRoute = AttemptsAttemptIdTimeUpRouteImport.update({
  id: '/attempts/$attemptId/time-up',
  path: '/attempts/$attemptId/time-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdRunRoute = AttemptsAttemptIdRunRouteImport.update({
  id: '/attempts/$attemptId/run',
  path: '/attempts/$attemptId/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdReviewRoute = AttemptsAttemptIdReviewRouteImport.update({
  id: '/attempts/$attemptId/review',
  path: '/attempts/$attemptId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdResultRoute = AttemptsAttemptIdResultRouteImport.update({
  id: '/attempts/$attemptId/result',
  path: '/attempts/$attemptId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdHandInRoute = AttemptsAttemptIdHandInRouteImport.update({
  id: '/attempts/$attemptId/hand-in',
  path: '/attempts/$attemptId/hand-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdSectionsSectionIdRulesRoute =
  AttemptsAttemptIdSectionsSectionIdRulesRouteImport.update({
    id: '/attempts/$attemptId/sections/$sectionId/rules',
    path: '/attempts/$attemptId/sections/$sectionId/rules',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/history': typeof HistoryRoute
  '/sign-in': typeof SignInRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/attempts/$attemptId/hand-in': typeof AttemptsAttemptIdHandInRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/attempts/$attemptId/review': typeof AttemptsAttemptIdReviewRoute
  '/attempts/$attemptId/run': typeof AttemptsAttemptIdRunRoute
  '/attempts/$attemptId/time-up': typeof AttemptsAttemptIdTimeUpRoute
  '/attempts/$attemptId/sections/$sectionId/rules': typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/history': typeof HistoryRoute
  '/sign-in': typeof SignInRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/attempts/$attemptId/hand-in': typeof AttemptsAttemptIdHandInRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/attempts/$attemptId/review': typeof AttemptsAttemptIdReviewRoute
  '/attempts/$attemptId/run': typeof AttemptsAttemptIdRunRoute
  '/attempts/$attemptId/time-up': typeof AttemptsAttemptIdTimeUpRoute
  '/attempts/$attemptId/sections/$sectionId/rules': typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/history': typeof HistoryRoute
  '/sign-in': typeof SignInRoute
  '/tests/$slug': typeof TestsSlugRoute
  '/attempts/$attemptId/hand-in': typeof AttemptsAttemptIdHandInRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/attempts/$attemptId/review': typeof AttemptsAttemptIdReviewRoute
  '/attempts/$attemptId/run': typeof AttemptsAttemptIdRunRoute
  '/attempts/$attemptId/time-up': typeof AttemptsAttemptIdTimeUpRoute
  '/attempts/$attemptId/sections/$sectionId/rules': typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/history'
    | '/sign-in'
    | '/tests/$slug'
    | '/attempts/$attemptId/hand-in'
    | '/attempts/$attemptId/result'
    | '/attempts/$attemptId/review'
    | '/attempts/$attemptId/run'
    | '/attempts/$attemptId/time-up'
    | '/attempts/$attemptId/sections/$sectionId/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/history'
    | '/sign-in'
    | '/tests/$slug'
    | '/attempts/$attemptId/hand-in'
    | '/attempts/$attemptId/result'
    | '/attempts/$attemptId/review'
    | '/attempts/$attemptId/run'
    | '/attempts/$attemptId/time-up'
    | '/attempts/$attemptId/sections/$sectionId/rules'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/history'
    | '/sign-in'
    | '/tests/$slug'
    | '/attempts/$attemptId/hand-in'
    | '/attempts/$attemptId/result'
    | '/attempts/$attemptId/review'
    | '/attempts/$attemptId/run'
    | '/attempts/$attemptId/time-up'
    | '/attempts/$attemptId/sections/$sectionId/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  HistoryRoute: typeof HistoryRoute
  SignInRoute: typeof SignInRoute
  TestsSlugRoute: typeof TestsSlugRoute
  AttemptsAttemptIdHandInRoute: typeof AttemptsAttemptIdHandInRoute
  AttemptsAttemptIdResultRoute: typeof AttemptsAttemptIdResultRoute
  AttemptsAttemptIdReviewRoute: typeof AttemptsAttemptIdReviewRoute
  AttemptsAttemptIdRunRoute: typeof AttemptsAttemptIdRunRoute
  AttemptsAttemptIdTimeUpRoute: typeof AttemptsAttemptIdTimeUpRoute
  AttemptsAttemptIdSectionsSectionIdRulesRoute: typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$slug': {
      id: '/tests/$slug'
      path: '/tests/$slug'
      fullPath: '/tests/$slug'
      preLoaderRoute: typeof TestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/time-up': {
      id: '/attempts/$attemptId/time-up'
      path: '/attempts/$attemptId/time-up'
      fullPath: '/attempts/$attemptId/time-up'
      preLoaderRoute: typeof AttemptsAttemptIdTimeUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/run': {
      id: '/attempts/$attemptId/run'
      path: '/attempts/$attemptId/run'
      fullPath: '/attempts/$attemptId/run'
      preLoaderRoute: typeof AttemptsAttemptIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/review': {
      id: '/attempts/$attemptId/review'
      path: '/attempts/$attemptId/review'
      fullPath: '/attempts/$attemptId/review'
      preLoaderRoute: typeof AttemptsAttemptIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/result': {
      id: '/attempts/$attemptId/result'
      path: '/attempts/$attemptId/result'
      fullPath: '/attempts/$attemptId/result'
      preLoaderRoute: typeof AttemptsAttemptIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/hand-in': {
      id: '/attempts/$attemptId/hand-in'
      path: '/attempts/$attemptId/hand-in'
      fullPath: '/attempts/$attemptId/hand-in'
      preLoaderRoute: typeof AttemptsAttemptIdHandInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/sections/$sectionId/rules': {
      id: '/attempts/$attemptId/sections/$sectionId/rules'
      path: '/attempts/$attemptId/sections/$sectionId/rules'
      fullPath: '/attempts/$attemptId/sections/$sectionId/rules'
      preLoaderRoute: typeof AttemptsAttemptIdSectionsSectionIdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  HistoryRoute: HistoryRoute,
  SignInRoute: SignInRoute,
  TestsSlugRoute: TestsSlugRoute,
  AttemptsAttemptIdHandInRoute: AttemptsAttemptIdHandInRoute,
  AttemptsAttemptIdResultRoute: AttemptsAttemptIdResultRoute,
  AttemptsAttemptIdReviewRoute: AttemptsAttemptIdReviewRoute,
  AttemptsAttemptIdRunRoute: AttemptsAttemptIdRunRoute,
  AttemptsAttemptIdTimeUpRoute: AttemptsAttemptIdTimeUpRoute,
  AttemptsAttemptIdSectionsSectionIdRulesRoute:
    AttemptsAttemptIdSectionsSectionIdRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
