/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as HistoryRouteImport } from './pages/history'
import { Route as AttemptsAttemptIdRunRouteImport } from './pages/attempts.$attemptId.run'
import { Route as AttemptsAttemptIdReviewRouteImport } from './pages/attempts.$attemptId.review'
import { Route as AttemptsAttemptIdResultRouteImport } from './pages/attempts.$attemptId.result'
import { Route as AttemptsAttemptIdHandInRouteImport } from './pages/attempts.$attemptId.hand-in'
import { Route as AttemptsAttemptIdSectionsSectionIdRulesRouteImport } from './pages/attempts.$attemptId.sections.$sectionId.rules'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdRunRoute = AttemptsAttemptIdRunRouteImport.update({
  id: '/attempts/$attemptId/run',
  path: '/attempts/$attemptId/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdReviewRoute = AttemptsAttemptIdReviewRouteImport.update({
  id: '/attempts/$attemptId/review',
  path: '/attempts/$attemptId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdResultRoute = AttemptsAttemptIdResultRouteImport.update({
  id: '/attempts/$attemptId/result',
  path: '/attempts/$attemptId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdHandInRoute = AttemptsAttemptIdHandInRouteImport.update({
  id: '/attempts/$attemptId/hand-in',
  path: '/attempts/$attemptId/hand-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsAttemptIdSectionsSectionIdRulesRoute =
  AttemptsAttemptIdSectionsSectionIdRulesRouteImport.update({
    id: '/attempts/$attemptId/sections/$sectionId/rules',
    path: '/attempts/$attemptId/sections/$sectionId/rules',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/history': typeof HistoryRoute
  '/attempts/$attemptId/hand-in': typeof AttemptsAttemptIdHandInRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/attempts/$attemptId/review': typeof AttemptsAttemptIdReviewRoute
  '/attempts/$attemptId/run': typeof AttemptsAttemptIdRunRoute
  '/attempts/$attemptId/sections/$sectionId/rules': typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}
export interface FileRoutesByTo {
  '/history': typeof HistoryRoute
  '/attempts/$attemptId/hand-in': typeof AttemptsAttemptIdHandInRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/attempts/$attemptId/review': typeof AttemptsAttemptIdReviewRoute
  '/attempts/$attemptId/run': typeof AttemptsAttemptIdRunRoute
  '/attempts/$attemptId/sections/$sectionId/rules': typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/history': typeof HistoryRoute
  '/attempts/$attemptId/hand-in': typeof AttemptsAttemptIdHandInRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/attempts/$attemptId/review': typeof AttemptsAttemptIdReviewRoute
  '/attempts/$attemptId/run': typeof AttemptsAttemptIdRunRoute
  '/attempts/$attemptId/sections/$sectionId/rules': typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/history'
    | '/attempts/$attemptId/hand-in'
    | '/attempts/$attemptId/result'
    | '/attempts/$attemptId/review'
    | '/attempts/$attemptId/run'
    | '/attempts/$attemptId/sections/$sectionId/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/history'
    | '/attempts/$attemptId/hand-in'
    | '/attempts/$attemptId/result'
    | '/attempts/$attemptId/review'
    | '/attempts/$attemptId/run'
    | '/attempts/$attemptId/sections/$sectionId/rules'
  id:
    | '__root__'
    | '/history'
    | '/attempts/$attemptId/hand-in'
    | '/attempts/$attemptId/result'
    | '/attempts/$attemptId/review'
    | '/attempts/$attemptId/run'
    | '/attempts/$attemptId/sections/$sectionId/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HistoryRoute: typeof HistoryRoute
  AttemptsAttemptIdHandInRoute: typeof AttemptsAttemptIdHandInRoute
  AttemptsAttemptIdResultRoute: typeof AttemptsAttemptIdResultRoute
  AttemptsAttemptIdReviewRoute: typeof AttemptsAttemptIdReviewRoute
  AttemptsAttemptIdRunRoute: typeof AttemptsAttemptIdRunRoute
  AttemptsAttemptIdSectionsSectionIdRulesRoute: typeof AttemptsAttemptIdSectionsSectionIdRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/run': {
      id: '/attempts/$attemptId/run'
      path: '/attempts/$attemptId/run'
      fullPath: '/attempts/$attemptId/run'
      preLoaderRoute: typeof AttemptsAttemptIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/review': {
      id: '/attempts/$attemptId/review'
      path: '/attempts/$attemptId/review'
      fullPath: '/attempts/$attemptId/review'
      preLoaderRoute: typeof AttemptsAttemptIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/result': {
      id: '/attempts/$attemptId/result'
      path: '/attempts/$attemptId/result'
      fullPath: '/attempts/$attemptId/result'
      preLoaderRoute: typeof AttemptsAttemptIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/hand-in': {
      id: '/attempts/$attemptId/hand-in'
      path: '/attempts/$attemptId/hand-in'
      fullPath: '/attempts/$attemptId/hand-in'
      preLoaderRoute: typeof AttemptsAttemptIdHandInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$attemptId/sections/$sectionId/rules': {
      id: '/attempts/$attemptId/sections/$sectionId/rules'
      path: '/attempts/$attemptId/sections/$sectionId/rules'
      fullPath: '/attempts/$attemptId/sections/$sectionId/rules'
      preLoaderRoute: typeof AttemptsAttemptIdSectionsSectionIdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HistoryRoute: HistoryRoute,
  AttemptsAttemptIdHandInRoute: AttemptsAttemptIdHandInRoute,
  AttemptsAttemptIdResultRoute: AttemptsAttemptIdResultRoute,
  AttemptsAttemptIdReviewRoute: AttemptsAttemptIdReviewRoute,
  AttemptsAttemptIdRunRoute: AttemptsAttemptIdRunRoute,
  AttemptsAttemptIdSectionsSectionIdRulesRoute:
    AttemptsAttemptIdSectionsSectionIdRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
